### ISSUE TITLE
Sizing of display to match monitor size

### ISSUE THREAD

**Issue by kongriley** [TanayB11/chinese-ocr#17]
Get rid of the scrollbar to fit the monitor's size completely.

**Comment by TanayB11** [comment]
Just pushed the changes, and they're also live on the demo page. It should look good for all but the tiniest monitor sizes now, let me know if it's good.

**Comment by TanayB11** [comment]
On the landing page there is going to be more information about the project and the app below the title component, so there's no need to fix the scrollbar.

**Comment by kongriley** [comment]
The scrollbar now appears duplicated on my display; one scrollbar is inactivated, while the other is scrollable. 
Monitor resolution: 1366 x 768, Windows 10

**Comment by TanayB11** [comment]
Ok, just added a max image width so it shouldn't overflow anymore. I don't have a Windows machine to test on, but on MacOS Brave (Chromium) using the device viewport emulator at 1366x768 there is no scrollbar.

**Comment by kongriley** [comment]
I've gotten the duplicate scrollbar issue to resolve, but the title screen is still improperly sized on my end. However, I think it's enough of a non-issue that I would consider this resolved.
